version: 1

update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'daily'

    default_reviewers:
      - 'brunobc182'
      - 'victorheringer'
    default_assignees:
      - 'brunobc182'
      - 'victorheringer'
